import { Restaurant } from "@/interface/Restaurant";

export const FILTERS = [
  "All",
  "French",
  "Japanese",
  "Italian",
  "Mediterranean",
  "Thai",
  "Indian",
  "Mexican",
  "Steakhouse",
  "Seafood",
  "Vegan",
  "Fusion",
  "Burger",
  "Dim Sum",
  "Ramen",
  "Cafe",
];

export const mockRestaurants: (Restaurant & {
  filter: string;
  description: string;
  tags: string[];
})[] = [
  {
    id: "65f1a2b3c4d5e6f7a8b9c001",
    name: "Toscana's Heart",
    category: "Classic Italian",
    location: "Little Italy",
    rating: 4.8,
    reviews: 150,
    imageSrc: "/restaurant/toscanas-heart.png",
    filter: "Italian",
    description: "A love letter to Northern Italy. Our handmade pastas are crafted fresh each morning, our truffles sourced from Alba, and our wine cellar holds over 800 Italian labels.",
    tags: ["Pasta Bar", "Truffle", "Italian Wine", "Handmade Pasta"],
  },
  {
    id: "65f1a2b3c4d5e6f7a8b9c002",
    name: "Tsunami Sushi",
    category: "Japanese Fusion",
    location: "Midtown East",
    rating: 4.9,
    reviews: 256,
    imageSrc: "/restaurant/tsunami-sushi.png",
    filter: "Japanese",
    description: "Where Tokyo precision meets New York energy. Our omakase experience features the freshest fish flown in daily from Toyosu Market, alongside innovative fusion dishes.",
    tags: ["Omakase", "Sake Bar", "Sushi", "Seasonal Menu"],
  },
  {
    id: "65f1a2b3c4d5e6f7a8b9c003",
    name: "Le Mistral",
    category: "French Bistro",
    location: "Upper East Side",
    rating: 4.7,
    reviews: 142,
    imageSrc: "/restaurant/le-mistral.png",
    filter: "French",
    description: "A flower-filled garden terrace that transports you to the 6th arrondissement. Classic bistro fare done with love — steak frites and soupe à l'oignon.",
    tags: ["Garden Terrace", "Classic Bistro", "Pet-Friendly", "Lunch"],
  },
  {
    id: "65f1a2b3c4d5e6f7a8b9c004",
    name: "Onyx Grill",
    category: "American Steakhouse",
    location: "Financial District",
    rating: 4.8,
    reviews: 412,
    imageSrc: "/restaurant/onyx-grill.png",
    filter: "Steakhouse",
    description: "An upscale steakhouse with dark wood walls, leather booths, and warm spotlighting on perfectly grilled steaks. Luxurious and bold flavor.",
    tags: ["Wood Fire", "Cocktails", "Steakhouse", "Craft Whiskey"],
  },
  {
    id: "65f1a2b3c4d5e6f7a8b9c005",
    name: "Verdant Valley",
    category: "Plant-Based Cafe",
    location: "West Village",
    rating: 4.6,
    reviews: 174,
    imageSrc: "/restaurant/verdant-valley.png",
    filter: "Vegan",
    description: "Bright and airy dining experience proving that plant-based cuisine can be just as luxurious and satisfying. Fresh from farm to table.",
    tags: ["Vegan", "Organic", "Tasting Menu", "Farm-to-Table"],
  },
  {
    id: "65f1a2b3c4d5e6f7a8b9c006",
    name: "Spicy Lotus",
    category: "Thai Street Food",
    location: "Queens, NY",
    rating: 4.8,
    reviews: 320,
    imageSrc: "/restaurant/spicy-lotus.png",
    filter: "Thai",
    description: "Vibrant Thai street food with colorful paper lanterns, steaming pots, and a busy night market atmosphere. Authentically Asian and energetic.",
    tags: ["Street Food", "Spicy", "Authentic Thai", "Busy"],
  },
  {
    id: "65f1a2b3c4d5e6f7a8b9c007",
    name: "Saffron Breeze",
    category: "Modern Indian",
    location: "Flatiron District",
    rating: 4.8,
    reviews: 203,
    imageSrc: "/restaurant/saffron-breeze.png",
    filter: "Indian",
    description: "Bold spices and unexpected textures reimagined through a modern fine-dining lens. A warm hospitality that feels like coming home.",
    tags: ["Tasting Menu", "Vegetarian Options", "Cocktail Pairing", "Modern Indian"],
  },
  {
    id: "65f1a2b3c4d5e6f7a8b9c008",
    name: "Adobe Kitchen",
    category: "Mexican Taqueria",
    location: "Lower East Side",
    rating: 4.7,
    reviews: 210,
    imageSrc: "/restaurant/adobe-kitchen.png",
    filter: "Mexican",
    description: "A lively Mexican taqueria with bright papel picado decorations and a cheerful atmosphere. The best carnitas in town.",
    tags: ["Tacos", "Margaritas", "Lively", "Festive"],
  },
  {
    id: "65f1a2b3c4d5e6f7a8b9c009",
    name: "Nebula Dining",
    category: "Modern Fusion",
    location: "TriBeCa",
    rating: 4.9,
    reviews: 185,
    imageSrc: "/restaurant/nebula-dining.png",
    filter: "Fusion",
    description: "A sophisticated modern fusion restaurant with futuristic lighting and creative plating. Sleek and high-end aesthetic.",
    tags: ["Fine Dining", "Innovative", "Artistic", "Sleek"],
  },
  {
    id: "65f1a2b3c4d5e6f7a8b9c010",
    name: "Iron Skillet Burgers",
    category: "Gourmet Burgers",
    location: "Brooklyn",
    rating: 4.7,
    reviews: 560,
    imageSrc: "/restaurant/iron-skillet-burgers.png",
    filter: "Burger",
    description: "A retro-styled burger joint with neon signs and a classic diner vibe. Hand-crafted burgers and artisanal milkshakes.",
    tags: ["Burgers", "Milkshakes", "Retro", "Casual"],
  },
  {
    id: "65f1a2b3c4d5e6f7a8b9c011",
    name: "Anchor & Brine",
    category: "Seafood Shack",
    location: "Battery Park",
    rating: 4.6,
    reviews: 310,
    imageSrc: "/restaurant/anchor-and-brine.png",
    filter: "Seafood",
    description: "A rustic seafood shack by the water. Our raw bar is the finest in the city, perfectly paired with harbor views.",
    tags: ["Seafood", "Oyster Bar", "Waterfront", "Casual"],
  },
  {
    id: "65f1a2b3c4d5e6f7a8b9c012",
    name: "Maru Ramen",
    category: "Japanese Ramen",
    location: "East Village",
    rating: 4.8,
    reviews: 440,
    imageSrc: "/restaurant/maru-ramen.png",
    filter: "Ramen",
    description: "A cozy Japanese ramen shop specializing in rich tonkotsu broth. Warm, authentic, and comforting.",
    tags: ["Ramen", "Quick Bite", "Authentic", "Cozy"],
  },
  {
    id: "65f1a2b3c4d5e6f7a8b9c013",
    name: "Azure Coast Grill",
    category: "Mediterranean Grill",
    location: "Chelsea",
    rating: 4.7,
    reviews: 198,
    imageSrc: "/restaurant/azure-coast-grill.png",
    filter: "Mediterranean",
    description: "Inspired by coastal villages, we bring the spirit of the Mediterranean to the city. Simple, fresh, and beautiful.",
    tags: ["Grill", "Healthy", "Mediterranean", "Terrace"],
  },
  {
    id: "65f1a2b3c4d5e6f7a8b9c014",
    name: "Jade Pavilion",
    category: "Authentic Dim Sum",
    location: "Chinatown",
    rating: 4.8,
    reviews: 620,
    imageSrc: "/restaurant/jade-pavilion.png",
    filter: "Dim Sum",
    description: "Traditional Chinese dim sum house with round tables and steaming baskets. Experience the true heart of Cantonese cuisine.",
    tags: ["Dim Sum", "Tea", "Traditional", "Large Groups"],
  },
  {
    id: "65f1a2b3c4d5e6f7a8b9c015",
    name: "Urban Roast",
    category: "Cozy Coffee Shop",
    location: "SoHo",
    rating: 4.9,
    reviews: 350,
    imageSrc: "/restaurant/urban-roast.png",
    filter: "Cafe",
    description: "A cozy neighborhood escape with soft sofas and exceptional coffee. The perfect spot to work or relax.",
    tags: ["Coffee", "Study Spot", "Cozy", "Pastries"],
  },
  {
    id: "65f1a2b3c4d5e6f7a8b9c016",
    name: "La Maison Dorée Luxe",
    category: "French Contemporary",
    location: "Downtown, Manhattan",
    rating: 4.9,
    reviews: 324,
    imageSrc: "/restaurant/la-maison-doree-luxe.jpg",
    filter: "French",
    description: "Classical French technique meets modern luxury. An unparalleled fine-dining journey in an elegant setting.",
    tags: ["Michelin ★★", "Tasting Menu", "Luxury", "Wine Bar"],
  },
  {
    id: "65f1a2b3c4d5e6f7a8b9c017",
    name: "Bella Trattoria",
    category: "Authentic Italian",
    location: "Little Italy",
    rating: 4.7,
    reviews: 180,
    imageSrc: "/restaurant/bella-trattoria.jpg",
    filter: "Italian",
    description: "Classic Italian dishes served in a warm, family-oriented atmosphere. Famous for our wood-fired pizzas and homemade tiramisu.",
    tags: ["Pizza", "Family Friendly", "Cozy", "Homemade"],
  },
  {
    id: "65f1a2b3c4d5e6f7a8b9c018",
    name: "El Matador",
    category: "Spanish Tapas",
    location: "Greenwich Village",
    rating: 4.6,
    reviews: 245,
    imageSrc: "/restaurant/el-matador.jpg",
    filter: "Mexican", // Closest filter available or I can add Spanish if preferred, but user said "more filters" earlier. I'll stick to Mexican or add Spanish later.
    description: "Experience the vibrant flavors of Spain with our authentic tapas and world-class sangria. A perfect spot for sharing plates with friends.",
    tags: ["Tapas", "Sangria", "Lively", "Small Plates"],
  },
  {
    id: "65f1a2b3c4d5e6f7a8b9c019",
    name: "La Maison Dorée",
    category: "Classic French",
    location: "Upper West Side",
    rating: 4.8,
    reviews: 195,
    imageSrc: "/restaurant/la-maison-doree.jpg",
    filter: "French",
    description: "The original La Maison Dorée experience. Traditional French elegance with a menu that celebrates the history of Gallic gastronomy.",
    tags: ["Fine Dining", "Romantic", "Classic French", "Elegant"],
  },
  {
    id: "65f1a2b3c4d5e6f7a8b9c020",
    name: "Oceano Blu",
    category: "Fresh Seafood",
    location: "Seaport District",
    rating: 4.7,
    reviews: 312,
    imageSrc: "/restaurant/oceano-blu.jpg",
    filter: "Seafood",
    description: "Sustainably sourced Mediterranean seafood prepared with simplicity and respect for the ingredients. Stunning harbor views included.",
    tags: ["Seafood", "Fresh Catch", "Harbor View", "Sustainable"],
  },
  {
    id: "65f1a2b3c4d5e6f7a8b9c021",
    name: "Sakura Garden",
    category: "Japanese Traditional",
    location: "Murray Hill",
    rating: 4.9,
    reviews: 278,
    imageSrc: "/restaurant/sakura-garden.jpg",
    filter: "Japanese",
    description: "A tranquil escape featuring traditional Japanese architecture and a serene rock garden. Specialized in Kaiseki and premium sake.",
    tags: ["Kaiseki", "Tranquil", "Traditional Japanese", "Sake"],
  },
  {
    id: "65f1a2b3c4d5e6f7a8b9c022",
    name: "The Golden Calf",
    category: "Premier Steakhouse",
    location: "Meatpacking District",
    rating: 4.8,
    reviews: 510,
    imageSrc: "/restaurant/the-golden-calf.jpg",
    filter: "Steakhouse",
    description: "Where old-school charm meets modern luxury. Dry-aged steaks prepared over cherrywood embers in a sophisticated, dimly lit setting.",
    tags: ["Dry-Aged", "High-End", "Steak", "Sophisticated"],
  },
];
